create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  brand text not null,
  category text not null,
  price numeric not null default 0,
  original_price numeric,
  label text not null default 'Nuevo',
  image_url text,
  description text,
  features text[] not null default '{}',
  recommended_for text,
  level text[] not null default '{}',
  play_style text not null default 'Equilibrio',
  weight text,
  is_offer boolean not null default false,
  stock integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.products enable row level security;

-- Lectura pública para el catálogo.
drop policy if exists "Public can read active products" on public.products;
create policy "Public can read active products"
on public.products
for select
using (is_active = true);

-- Solo usuarios autenticados pueden administrar productos.
drop policy if exists "Authenticated users can insert products" on public.products;
create policy "Authenticated users can insert products"
on public.products
for insert
to authenticated
with check (true);

drop policy if exists "Authenticated users can update products" on public.products;
create policy "Authenticated users can update products"
on public.products
for update
to authenticated
using (true)
with check (true);

drop policy if exists "Authenticated users can delete products" on public.products;
create policy "Authenticated users can delete products"
on public.products
for delete
to authenticated
using (true);

create index if not exists products_category_idx on public.products(category);
create index if not exists products_brand_idx on public.products(brand);
create index if not exists products_is_active_idx on public.products(is_active);
