-- Ejecutar una sola vez en Supabase > SQL Editor.
-- Agrega múltiples fotos por producto sin modificar products.image_url,
-- que continúa siendo la portada principal del catálogo.

create table if not exists public.product_images (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  image_url text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.product_images enable row level security;

drop policy if exists "Public can read product images" on public.product_images;
create policy "Public can read product images"
on public.product_images
for select
using (true);

drop policy if exists "Authenticated users can insert product images" on public.product_images;
create policy "Authenticated users can insert product images"
on public.product_images
for insert
to authenticated
with check (true);

drop policy if exists "Authenticated users can update product images" on public.product_images;
create policy "Authenticated users can update product images"
on public.product_images
for update
to authenticated
using (true)
with check (true);

drop policy if exists "Authenticated users can delete product images" on public.product_images;
create policy "Authenticated users can delete product images"
on public.product_images
for delete
to authenticated
using (true);

create index if not exists product_images_product_id_idx on public.product_images(product_id);
create index if not exists product_images_sort_order_idx on public.product_images(product_id, sort_order);
